#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=thespelltheritualtheanthem-by-wildbashkortmages

APP_FULLNAME="THE SPELL, THE RITUAL, THE ANTHEM"
APP_COPYRIGHT="WILD BASHKORT MAGES"
APP_DESC="demo by WILD BASHKORT MAGES released in 2015"

APP_EXE="bashkortostan"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
