./assets/voxel/ usr/share/unit-by-petterroeaanddolphin/assets/
./assets/cube.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/vignette.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/water.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/greets.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/skybox_grid.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/cube_inverted.png usr/share/unit-by-petterroeaanddolphin/assets/
./assets/*.flac usr/share/unit-by-petterroeaanddolphin/assets/
