#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=semtexcity-by-jeskolaproduction

APP_FULLNAME=" Semtex City"
APP_COPYRIGHT="Jeskola! Productions"
APP_DESC="demo ranked 1st at Juhla 1995"
APP_EXE="SEMTEX.EXE"
APP_SETSOUND="SEMTEX.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "SEMTEX.MOD" "SEMTEX.MOD"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
