#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=semtexcity-by-jeskolaproduction

APP_FULLNAME=" Semtex City"
APP_COPYRIGHT="Jeskola! Productions"
APP_DESC="demo ranked 1st at Juhla 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "SEMTEX.MOD" "SEMTEX.MOD"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
