#! /bin/bash

wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/build
wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/libhxcadaptor/trunk
wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/libhxcfe/trunk
wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/libusbhxcfe/trunk
wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/HxCFloppyEmulator_cmdline/trunk
wget  https://sourceforge.net/p/hxcfloppyemu/code/2236/tarball?path=/HxCFloppyEmulator/HxCFloppyEmulator_software/trunk

unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-build.zip
unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-libhxcadaptor-trunk.zip
unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-libhxcfe-trunk.zip
unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-libusbhxcfe-trunk.zip
unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-HxCFloppyEmulator_cmdline-trunk.zip
unzip hxcfloppyemu-code-r2236-HxCFloppyEmulator-HxCFloppyEmulator_software-trunk.zip

mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-build build
mkdir libhxcadaptor
mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-libhxcadaptor-trunk libhxcadaptor/trunk
mkdir libhxcfe
mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-libhxcfe-trunk libhxcfe/trunk
mkdir libusbhxcfe
mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-libusbhxcfe-trunk libusbhxcfe/trunk
mkdir HxCFloppyEmulator_cmdline
mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-HxCFloppyEmulator_cmdline-trunk HxCFloppyEmulator_cmdline/trunk
mkdir HxCFloppyEmulator_software
mv hxcfloppyemu-code-r2236-HxCFloppyEmulator-HxCFloppyEmulator_software-trunk HxCFloppyEmulator_software/trunk
