#! /bin/bash

wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-build.zip
wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcadaptor-trunk.zip
wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcfe-trunk.zip
wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-libusbhxcfe-trunk.zip
wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_cmdline-trunk.zip
wget https://sourceforge.net/code-snapshots/svn/h/hx/hxcfloppyemu/code/hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_software-trunk.zip

unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-build.zip
unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcadaptor-trunk.zip
unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcfe-trunk.zip
unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-libusbhxcfe-trunk.zip
unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_cmdline-trunk.zip
unzip hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_software-trunk.zip

mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-build build
mkdir libhxcadaptor
mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcadaptor-trunk libhxcadaptor/trunk
mkdir libhxcfe
mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-libhxcfe-trunk libhxcfe/trunk
mkdir libusbhxcfe
mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-libusbhxcfe-trunk libusbhxcfe/trunk
mkdir HxCFloppyEmulator_cmdline
mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_cmdline-trunk HxCFloppyEmulator_cmdline/trunk
mkdir HxCFloppyEmulator_software
mv hxcfloppyemu-code-r2007-HxCFloppyEmulator-HxCFloppyEmulator_software-trunk HxCFloppyEmulator_software/trunk
