#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=thekillingofanegg-by-slimproductions

APP_FULLNAME="The Killing of an Egg"
APP_COPYRIGHT="Slim Productions"
APP_DESC="Intro ranked 5th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
