#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=wateengorekop-by-quartex

APP_FULLNAME="Wat Een Gore Kop"
APP_COPYRIGHT="Quartex"
APP_DESC="Intro ranked 18th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
