#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=pureness-by-waterlogic

APP_FULLNAME="Pureness"
APP_COPYRIGHT="Waterlogic"
APP_DESC="demo ranked 1st at The Scene 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "WATERLOG.IC!" "WATERLOG.IC!"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
