#!/bin/bash -e

domain=win32-stigma-by-emotive

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

function prerun()
{
	NSH_CreateTmpDomainDir
    NSH_InstallRWFileInTmp Data/Bol.msh Bol.msh
	NSH_InstallRWFileInTmp Data/Hedra.msh Hedra.msh
	NSH_InstallRWFileInTmp Data/Scape1.map Scape1.map
	NSH_InstallRWFileInTmp Data/Stekels.msh Stekels.msh
	NSH_InstallRWFileInTmp Data/Scape2.map Scape2.map
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_wine
