#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=falling-by-realitybytes-amiga-whd

APP_FULLNAME="falling"
APP_COPYRIGHT="Reality Bytes"
APP_DESC="AGA intro by Reality Bytes released at Icing 1999"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
