#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lethalexit-by-digital-disk

APP_FULLNAME="Lethal Exit"
APP_COPYRIGHT="Digital"
APP_DESC="demo released: 1992-12-29 on The Party 1992"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
