.TH "anrufausschweden\-by\-unik" "6" "2016\-03\-20" "anruf aus schweden User Manuals" ""
.SH NAME
.PP
anrufausschweden\-by\-unik \- is the command to run anruf aus schweden
.SH SYNOPSIS
.PP
anrufausschweden\-by\-unik [\f[I]options\f[]]
.SH DESCRIPTION
.PP
anruf aus schweden is a demonstration released by unik Demo by unik,
released in 2004
.SH OPTIONS
.PP
there is no options to this program
.SH BUGS
.PP
No known bugs.
.SH AUTHORS
Nicolas HOUDELOT (nicolas\@demosdebs.org),unik.
