#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=calimero-by-paradoxandthefrogbuds

APP_FULLNAME="Calimero"
APP_COPYRIGHT="Paradox and The Frog Buds"
APP_DESC="intro ranked 9th at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
