#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fullmoon-by-virtualdreamsandfairlight

APP_FULLNAME="Fullmoon"
APP_COPYRIGHT="Virtual Dreams and Fairlight"
APP_DESC="Demo ranked 2nd at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
