#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=whenwerideinourenemies-by-skarla

APP_FULLNAME="when we ride on our enemies"
APP_COPYRIGHT="skarla"
APP_DESC="Demo ranked 2nd at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
