#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=bythepond-by-tkln

APP_FULLNAME="By the Pond"
APP_COPYRIGHT="tkln"
APP_DESC="Demo by tkln, released in 2018"

APP_EXE="by_the_pond_by_tkln"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
