#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=x14-by-orange

APP_FULLNAME="x14"
APP_COPYRIGHT="orange"
APP_DESC="demo ranked 1st at Juhla2 1995"
APP_EXE="X14.EXE"
APP_SETSOUND="X14.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "DATA.DAT" "DATA.DAT"
	NSH_InstallRWFileInTmp "X14.S3M" "X14.S3M"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
