#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=x14-by-orange

APP_FULLNAME="x14"
APP_COPYRIGHT="orange"
APP_DESC="demo ranked 1st at Juhla2 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "DATA.DAT" "DATA.DAT"
	NSH_InstallRWFileInTmp "X14.S3M" "X14.S3M"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
