#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=quest-by-iris

APP_FULLNAME="quest"
APP_COPYRIGHT="IRIS"
APP_DESC="Demo ranked 5th at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
