#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=no-by-polkabrothers

APP_FULLNAME="No!"
APP_COPYRIGHT="Polka Brothers"
APP_DESC="Demo ranked 9th at The Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
