#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nostalgia-by-gnb

APP_FULLNAME="Nostalgia"
APP_COPYRIGHT="G'n'B"
APP_DESC="demo by G'n'B released in 2012"

APP_EXE="Nostalgia.release"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
