#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=lemuseum-by-jff

APP_FULLNAME="Le Museum"
APP_COPYRIGHT="Just For Fun"
APP_DESC="intro released at Slach Party 2001"
APP_EXE="JFF-MUSE.EXE"
APP_SETSOUND="JFF-MUSE.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "JFF-MUSE.EXE" "JFF-MUSE.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
