#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=salvationmind-by-moment22

APP_FULLNAME="Salvation Mind"
APP_COPYRIGHT="Moment 22"
APP_DESC="Intro ranked 24th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
