#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=vividexperiment-by-doomsday

APP_FULLNAME="Vivid Experiment"
APP_COPYRIGHT="doomsday"
APP_DESC="demo ranked 3rd at Assembly 1996"
APP_EXE="VIVID.EXE"
APP_SETSOUND="VIVID.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
