#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=teh4k3000-by-theolddude

APP_FULLNAME="Teh 4k 3000"
APP_COPYRIGHT="the old dude"
APP_DESC="demo by the old dude released in 2011"

APP_EXE="teh4k -w"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
