#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=closetothedestination-by-thebadsectors

APP_FULLNAME="Close to the destination"
APP_COPYRIGHT="The Bad Sectors"
APP_DESC="demo by The Bad Sectors released in 2009"

APP_EXE="tbs-close-linux-64bit.lnx"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
