#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=kriskrossucks-by-kefrens

APP_FULLNAME="Kris Kros Sucks"
APP_COPYRIGHT="Kefrens"
APP_DESC="demo released in 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
