#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=exine-by-anarchy

APP_FULLNAME="Exine"
APP_COPYRIGHT="Anarchy"
APP_DESC="demo ranked 2nd at volcanic 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
