#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=guillotine-by-dajormas

APP_FULLNAME="guillotine"
APP_COPYRIGHT="da Jormas"
APP_DESC="Demo ranked 7th at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
