#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=metachronie-by-mirage

APP_FULLNAME="Metachronie"
APP_COPYRIGHT="Mirage"
APP_DESC="demo by Mirage released in 2012"

APP_EXE="metachronie-linux_x86-64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
