#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=primary-by-qaz

APP_FULLNAME="Primary"
APP_COPYRIGHT="Qaz"
APP_DESC="demo by Qaz released in 2010"

APP_EXE="qaz-primary-linux -w 1280 -h 720"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
