#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=pyrox-by-bizarrearts

APP_FULLNAME="Pyrox"
APP_COPYRIGHT="bizarre arts"
APP_DESC="Intro ranked 9th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
