#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=response-by-avalon

APP_FULLNAME="Response"
APP_COPYRIGHT="Avalon"
APP_DESC="Demo ranked 2nd at The Gathering 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
