#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lisa-by-eclipse

APP_FULLNAME="Lisa"
APP_COPYRIGHT="Eclipse"
APP_DESC="demo ranked 1st at Gasp 1995"
APP_EXE="LISA.EXE"
APP_SETSOUND="LISA.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "LISA.EXE" "LISA.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
