#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=extension-by-pygmyprojects-amiga-whd

APP_FULLNAME="Extension"
APP_COPYRIGHT="Pygmy Projects"
APP_DESC="demo by Pygmy Projects released in 1993"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
