#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=tungsram-by-haujobb

APP_FULLNAME="tungsram"
APP_COPYRIGHT="Haujobb"
APP_DESC="demo ranked 1st by Haujobb"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
