#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=falco-by-cryogen

APP_FULLNAME="Falco"
APP_COPYRIGHT="Cryogen"
APP_DESC="intro ranked 9th at Mekka & Symposium 2000"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
