#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=alpenclub52-by-depth

APP_FULLNAME="alpenclüb '52"
APP_COPYRIGHT="depth"
APP_DESC="Demo ranked 6th at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
