#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=voyage-by-razor1911-disk

APP_FULLNAME="voyage"
APP_COPYRIGHT="Razor 1911"
APP_DESC="demo ranked 3rd at The Party 1991"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
