#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=bigtimesensuality-by-axis-whdload

APP_FULLNAME="big time sensuality"
APP_COPYRIGHT="Axis"
APP_DESC="demo released in march 1994"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
