#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=4k0-by-polkabrothers

APP_FULLNAME="4k0"
APP_COPYRIGHT="Polka Brothers"
APP_DESC="intro ranked 1st at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
