#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=darkhour-by-sistavipcorporation

APP_FULLNAME="Dark Hour"
APP_COPYRIGHT="Sista Vip Corporation"
APP_DESC="demo ranked 21st at Mekka & Symposium 2000"
APP_EXE="DOSDARK.EXE"
APP_SETSOUND="DOSDARK.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_CopyDirInTmp .
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
