#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=entropia-by-exmortis

APP_FULLNAME="Entropia"
APP_COPYRIGHT="Exmortis"
APP_DESC="demo ranked 1st at General Probe 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
