#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=mindyourhead-by-macslow

APP_FULLNAME="Mind your head"
APP_COPYRIGHT="MacSlow"
APP_DESC="Demo by MacSlow, released in 2019"

APP_EXE="mind-your-head_by_MacSlow-fullscreen-1920x1080"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
