#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=authentik-by-skarla

APP_FULLNAME="Authentik"
APP_COPYRIGHT="Skarla"
APP_DESC="demo discalified at The Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
