#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=witpremium-by-freezers

APP_FULLNAME="Wit Premium"
APP_COPYRIGHT="Freezers"
APP_DESC="demo ranked 2nd at Gelloween 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
