#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=claudia-by-deathstar

APP_FULLNAME="Claudia"
APP_COPYRIGHT="Deathstar"
APP_DESC="demo ranked 1st at Mekka & Symposium 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
