#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=claudia-by-deathstar

APP_FULLNAME="Claudia"
APP_COPYRIGHT="Deathstar"
APP_DESC="demo ranked 1st at Mekka & Symposium 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

