#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=hospitalsincefriday-by-sanity

APP_FULLNAME="Hospital Since Friday"
APP_COPYRIGHT="Sanity"
APP_DESC="intro ranked 15th at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
