#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=deep-by-parallaxandcncd

APP_FULLNAME="Deep"
APP_COPYRIGHT="Parallax, Carillon and Cyberlad"
APP_DESC="Demo ranked 1st at The Gathering 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
