#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=solstice-by-valhalla

APP_FULLNAME="Solstice"
APP_COPYRIGHT="Valhalla"
APP_DESC="demo ranked 1st at Wired 1995"
APP_EXE="SOLSTICE.EXE"
APP_SETSOUND="SOLSTICE.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
