#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nordtroxyiiinvitation-by-frobnicators

APP_FULLNAME="NordtroXy II Invitation"
APP_COPYRIGHT="Frobnicators"
APP_DESC="demo by Frobnicators released in 2012"

APP_EXE="run.sh"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
