#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=planetgroove-by-fudge

APP_FULLNAME="planet groove"
APP_COPYRIGHT="fudge"
APP_DESC="demo Ranked 20th at The Party 1995"
APP_EXE="GROOVE.EXE"
APP_SETSOUND="GROOVE.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "GROOVE.EXE" "GROOVE.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
