#!/bin/bash -e

domain=win32-fairplaytothequeen-by-candela

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

APP_FULLNAME="Fair play to the queen"
APP_COPYRIGHT="Candela"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_wine2
