#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lola-by-freshprince

APP_FULLNAME="Lola (McIntro)"
APP_COPYRIGHT="Fresh Prince"
APP_DESC="Intro ranked 2nd at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
