#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=explicit-by-hornet-otm

APP_FULLNAME="Explicit"
APP_COPYRIGHT="Hornet & OTM"
APP_DESC="demo Ranked 3rd at NAID 1996"
APP_EXE="EXPLICIT.EXE"
APP_SETSOUND="EXPLICIT.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_CopyDirInTmp .
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
