#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=explicit-by-hornet-otm

APP_FULLNAME="Explicit"
APP_COPYRIGHT="Hornet & OTM"
APP_DESC="demo Ranked 3rd at NAID 1996"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_CopyDirInTmp .
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

