#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=acme-syw-by-acme

APP_FULLNAME="ACME Smoke Yellow Weed"
APP_COPYRIGHT="Acme"
APP_DESC="intro 64k ranked 1st at Somewhere in Holland 1995"
APP_EXE="ACME-SYW.EXE"
APP_SETSOUND="ACME-SYW.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
