#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=funtro3-by-universe

APP_FULLNAME="Funtro-3"
APP_COPYRIGHT="UniVerse"
APP_DESC="intro ranked 3rd at ByteFall 1999"
APP_EXE="FUNTRO3!.EXE"
APP_SETSOUND="FUNTRO3!.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "MUSIC2.S3M" "MUSIC2.S3M"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
