#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=funtro3-by-universe

if [ $(which gettext) ]; then
	gettext="gettext --domain=$domain -s --"
else
	gettext=echo
fi

function usage()
{
	$gettext "Usage: funtro3-by-universe [OPTION]"
	$gettext "Start Funtro-3 - intro ranked 3rd at ByteFall 1999"
	echo
	$gettext "--help       display this help and exit"
	$gettext "--fullscreen	start demo in fullscreen (Ctrl-F9 to exit)"
	$gettext "--debug	start the dosbox environnement without running the demo"
	$gettext "--version    display version information and exit"
}

function version()
{
	$gettext "funtro3-by-universe"
	$gettext "Copyright (C) UniVerse "
	$gettext "Dosbox Copyright (C) Dosbox Team"
}

function run()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp MUSIC2.S3M MUSIC2.S3M
	/usr/bin/dosbox-x -conf  /usr/share/$domain/$1.conf $2
	NSH_RemoveTmpDomainDir
}

function run_debug()
{
	NSH_SetDebugDOSBOX
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp MUSIC2.S3M MUSIC2.S3M
	/usr/bin/dosbox-x -conf  /tmp/$1_debug.conf
	NSH_RemoveTmpDomainDir
	NSH_RemoveDebugDOSBOX
}

if [ "$#" -gt "1" ]; then
	usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run $domain
else
	case "$1" in
	--help)
		usage
		;;
	--fullscreen)
		run $domain -fullscreen
		;;
	--debug)
		run_debug $domain
		;;
	--version)
		version
		;;
	*)
		usage
		exit 1
		;;
	esac
fi

exit 0
