.TH "xa005spike\-by\-xangle" "6" "2016\-03\-31" "xa\-005: Spike User Manuals" ""
.SH NAME
.PP
xa005spike\-by\-xangle \- is the command to run xa\-005: Spike
.SH SYNOPSIS
.PP
xa005spike\-by\-xangle [\f[I]options\f[]]
.SH DESCRIPTION
.PP
xa\-005: Spike is a demonstration released by xAngle Demo by xAngle,
released in 2005
.SH OPTIONS
.PP
there is no options to this program
.TP
.B \-\-help
Display help for the command
.RS
.RE
.SH BUGS
.PP
No known bugs.
.SH AUTHORS
Nicolas HOUDELOT (nicolas\@demosdebs.org),xAngle.
