#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=magiccarpet-by-keenlikefrogs

APP_FULLNAME="Magic Carpet"
APP_COPYRIGHT="Keen Like Frogs"
APP_DESC="intro ranked 1st at Wired 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
    touch /tmp/$domain/___KLF__.EXE
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
