#!/bin/bash -e

domain=win32-sx7302-by-darkeden

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

if [ "$#" -gt "3" ]; then
	NSH_std_usage_WINE
	exit 1
elif [ "$#" -lt "1" ]; then
	if [ ! -e "$HOME/.PlayOnLinux/shortcuts/$APP_FULLNAME" ]
	then
		export polscreenmode
		export polwine
		NSH_prepare_std_first_run_WINE
		NSH_std_run_WINE
	else 
		NSH_std_run_WINE
	fi
else
	case "$1" in
	--help)
		NSH_std_usage_WINE
		;;
	--version)
		NSH_version_WINE
		;;
	--setdesktop)
		export polscreenmode="desktop"
		export polwine
		NSH_prepare_std_first_run_WINE
		;;
	--setwindow)
		export polscreenmode="window"
		export polwine
		NSH_prepare_std_first_run_WINE
		;;
	--setwine)
		if [ -z "$2" ]
		then
			NSH_std_usage_WINE
			exit 1
		fi
		export polscreenmode
		export polwine="$2"
		NSH_prepare_std_first_run_WINE
		;;
	--reset)
		export polscreenmode
		export polwine
		NSH_prepare_std_first_run_WINE
		;;
	*)
		NSH_std_usage_WINE
		exit 1
		;;
	esac
fi

exit 0
