#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=jellyfishthejam-by-capsadminandjimbo

APP_FULLNAME=" Jellyfish: The Jam"
APP_COPYRIGHT="CapsAdmin and Jimbo"
APP_DESC="demo by CapsAdmin and Jimbo released in 2015"

APP_EXE="luajit jellyfish_demo.lua"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain} || exit
	${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
