#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=frenchiesintro-by-thefrenchies-atari

APP_FULLNAME="Frenchies intro"
APP_COPYRIGHT="The Frenchies"
APP_DESC="demo by The Frenchies released in 2004"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/${domain}/harddrive
}

source /usr/share/common-install-function-ddebs/endscript_atarist
