#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=frenchiesintro-by-thefrenchies-atari

APP_FULLNAME="Frenchies intro"
APP_COPYRIGHT="The Frenchies"
APP_DESC="demo by The Frenchies released in 2004"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/${domain}/harddrive
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage_ATARI
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage_ATARI
		;;
	--fullscreen)
		run --fullscreen
		;;
	--version)
		NSH_version_ATARI
		;;
	*)
		NSH_std_usage_ATARI
		exit 1
		;;
	esac
fi

exit 0
