#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=nation0part2-by-jamm

APP_FULLNAME="Nation 0 part 2"
APP_COPYRIGHT="jamm"
APP_DESC="intro Ranked 3rd at Assembly 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
