#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=arte-by-sanity-disk

APP_FULLNAME="Arte"
APP_COPYRIGHT="Sanity"
APP_DESC="demo ranked 3rd at The Party 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
