#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=technologicaldeath-by-madelks-disk

APP_FULLNAME="Technological Death"
APP_COPYRIGHT="mad elks"
APP_DESC="demo ranked 1st at  Mountain Congress 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
