#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=technologicaldeath-by-madelks-disk

APP_FULLNAME="Technological Death"
APP_COPYRIGHT="mad elks"
APP_DESC="demo ranked 1st at  Mountain Congress 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
