#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=engagethefresse-by-stroboholics

APP_FULLNAME="ENGAGE THE FRESSE"
APP_COPYRIGHT="stroboholics"
APP_DESC="demo by stroboholics released in 2010"

APP_EXE="strobo-windowed-64bit"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
