#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=cherrycherrysquarewave-by-funnycurlycatcodefactory

APP_FULLNAME="Cherry Cherry Square Wave"
APP_COPYRIGHT="Funny Curly Cat Code Factory"
APP_DESC="Demo by Funny Curly Cat Code Factory, released in 2019"

APP_EXE="ccsq_fixed_audio"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
