#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=xenophobia-by-subspace

APP_FULLNAME="xenophobia"
APP_COPYRIGHT="Subspace"
APP_DESC="demo ranked 2nd at Icing Beta 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
