.TH "glrez\-by\-rez" "6" "2016\-03\-28" "glRez User Manuals" ""
.SH NAME
.PP
glrez\-by\-rez \- is the command to run glRez
.SH SYNOPSIS
.PP
glrez\-by\-rez [\f[I]options\f[]]
.SH DESCRIPTION
.PP
glRez is a demonstration released by rez Demo by rez, released in 2005
.SH OPTIONS
.PP
there is no options to this program
.TP
.B \-\-help
Display help for the command
.RS
.RE
.SH BUGS
.PP
No known bugs.
.SH AUTHORS
Nicolas HOUDELOT (nicolas\@demosdebs.org),rez.
