#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fieldtrip-by-lft

APP_FULLNAME="Field Trip"
APP_COPYRIGHT="lft"
APP_DESC="demo by lft released in 2007"
APP_EXE="field_trip_by_lft"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE} -w
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
