#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=aurora-by-stellar

APP_FULLNAME="Aurora"
APP_COPYRIGHT="Stellar"
APP_DESC="demo ranked 1st at Scenario 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
