#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=juhlaivb-invitation-by-doomsday-byterapers

APP_FULLNAME="Juhla IVb Invitation"
APP_COPYRIGHT="doomsday & Byterapers"
APP_DESC="intro invitation to Juhla 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
