#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=odyssey-by-alcatraz

APP_FULLNAME="Odyssey"
APP_COPYRIGHT="Alcatraz"
APP_DESC="demo ranked 1st at The Party 1991"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
