#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=test-by-sigflup

APP_FULLNAME="test"
APP_COPYRIGHT="SigFLUP"
APP_DESC="Demo by SigFLUP, released in 2017"

APP_EXE="test"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
