#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=horison4k-by-nocturnal

APP_FULLNAME="horison 4k"
APP_COPYRIGHT="Nocturnal"
APP_DESC="4k intro ranked 11th at The Gathering 1999"
APP_EXE="HORISON.COM"
APP_SETSOUND="HORISON.COM"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
