#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=love-by-virtualdreamsfairlight

APP_FULLNAME="Love"
APP_COPYRIGHT="Virtual Dreams and Fairlight"
APP_DESC="Demo ranked 1st at South Sealand Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
