#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lunareactivation-by-vovoid

APP_FULLNAME="Luna : Reactivation"
APP_COPYRIGHT="vovoid"
APP_DESC="demo by vovoid released in 2011"

APP_EXE="vovoid-luna:reactivation.sh"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain}
	LD_LIBRARY_PATH="/usr/lib/i386-linux-gnu/${domain}/demo/" ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
