#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=darkroom-by-stellar

APP_FULLNAME="darkroom"
APP_COPYRIGHT="Stellar"
APP_DESC="intro ranked 3rd at Assembly 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
