#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=secondreality-by-futurecrew

APP_FULLNAME="Second Reality"
APP_COPYRIGHT="Future Crew"
APP_DESC="demo by Future Crew released in 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
