#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=bomb-by-dentifrice

APP_FULLNAME="Second Reality"
APP_COPYRIGHT="Future Crew"
APP_DESC="demo by Future Crew released in 1993"

function prerun()
{
	NSH_CreateTmpDomainDir
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
