#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=bomb-by-dentifrice

APP_FULLNAME="Second Reality"
APP_COPYRIGHT="Future Crew"
APP_DESC="demo by Future Crew released in 1993"

function prerun()
{
	NSH_CreateTmpDomainDir
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
