#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=styggtro-by-andromeda

APP_FULLNAME="Styggtro"
APP_COPYRIGHT="Andromeda"
APP_DESC="intro ranked 5th at The Gathering 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
