#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=suitafutura-by-liberty

APP_FULLNAME="Suita Futura"
APP_COPYRIGHT="Liberty"
APP_DESC="demo ranked 2nd at Gravity 1998"
APP_EXE="SUITA.EXE"
APP_SETSOUND="SUITA.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
