#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=pretaporter-by-concept

APP_FULLNAME="Pret a porter"
APP_COPYRIGHT="Concept"
APP_DESC="intro ranked 1st at Fallas Party 2000"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
