#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=away-by-genesis

APP_FULLNAME="Away"
APP_COPYRIGHT="Genesis"
APP_DESC="Demo ranked 1st at Trip 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
