#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=palikka-by-moottori

APP_FULLNAME="Palikka"
APP_COPYRIGHT="Moottori"
APP_DESC="intro ranked 4th at assembly 1996"
APP_EXE="TEXTDEMO.EXE"
APP_SETSOUND="TEXTDEMO.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
