#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=cuboidholiday-by-mikkosoftproductionsquadtrip

APP_FULLNAME="Cuboid Holiday"
APP_COPYRIGHT="Mikkosoft Productions & Quadtrip"
APP_DESC="Demo by Mikkosoft Productions & Quadtrip, released in 2019"
APP_EXE="graffathon2019"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
