#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=thedrunkdesertdemo-by-paradox

APP_FULLNAME="The Drunk Desert Demo"
APP_COPYRIGHT="Paradox"
APP_DESC="Demo by Paradox,released in 1990"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
