#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=b14-by-vantagemfx

APP_FULLNAME="B.14"
APP_COPYRIGHT="Vantage & mfx"
APP_DESC="demo by Vantage & mfx released in 2005"
APP_EXE="vtg_b14"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	LD_LIBRARY_PATH=. ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
