#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=babelfish-by-thesiriuscyberneticscorporation-atari

APP_FULLNAME="Babelfish"
APP_COPYRIGHT="The Sirius Cybernetics Corporation"
APP_DESC="demo by The Sirius Cybernetics Corporation released in 1998"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/$domain/harddrive
}

source /usr/share/common-install-function-ddebs/endscript_atarist
