#!/bin/bash -e

source common-install-function

domain=babelfish-by-thesiriuscyberneticscorporation-atari

APP_FULLNAME="Babelfish"
APP_COPYRIGHT="The Sirius Cybernetics Corporation"
APP_DESC="demo by The Sirius Cybernetics Corporation released in 1998"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d ../../harddrive
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage_ATARI
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage_ATARI
		;;
	--fullscreen)
		run --fullscreen
		;;
	--version)
		NSH_version_ATARI
		;;
	*)
		NSH_std_usage_ATARI
		exit 1
		;;
	esac
fi

exit 0
