#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=archytas-by-peisik

APP_FULLNAME="Archytas"
APP_COPYRIGHT="Peisik"
APP_DESC="demo by Peisik released in 2011"

APP_EXE="archytas_720p_windowed"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
