#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=supa-by-mrp

APP_FULLNAME="supa"
APP_COPYRIGHT="mrp"
APP_DESC="demo by mrp released in 2008"

APP_EXE="supa"

function run()
{
	backuppwd=$(pwd)
	ln -s /usr/lib/i386-linux-gnu/${domain}/supa /tmp/supa
	cd /tmp
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}  || true
	rm /tmp/${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
