#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=guggleme-by-doomsday

APP_FULLNAME="Guggle me !"
APP_COPYRIGHT="doomsday"
APP_DESC="demo ranked 2nd at Skenery 1996"
APP_EXE="GUGGLEME.EXE"
APP_SETSOUND="GUGGLEME.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
