#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nightdrive-by-contraz

APP_FULLNAME="Night Drive"
APP_COPYRIGHT="Contraz"
APP_DESC="demo by Contraz released in 2013"

APP_EXE="NightDrive"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	LD_LIBRARY_PATH=. ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
