#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=summerhack-by-thelab

APP_FULLNAME="Summer Hack"
APP_COPYRIGHT="the Lab"
APP_DESC="demo by the Lab released the 2005"
APP_EXE="sumhack-gnulinux-x86_64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}/
	./${APP_EXE}
	cd $backuppwd
	
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
