#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=magicbiniou-by-eclipse

APP_FULLNAME="Magic Biniou"
APP_COPYRIGHT="Eclipse"
APP_DESC="demo ranked 1st at volcanic 1996"
APP_EXE="MAGIC.EXE"
APP_SETSOUND="MAGIC.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
