#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=electromagnetic-by-hackers

APP_FULLNAME="Electro-Magnetic"
APP_COPYRIGHT="Hackers"
APP_DESC="16k intro by Hackers, released in 2016"

APP_EXE="player"

function run()
{
	backuppwd=$(pwd)
	cd  /usr/lib/i386-linux-gnu/${domain}
	SDL_VIDEODRIVER=x11 SDL12COMPAT_OPENGL_SCALING=0 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
