#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=pinp-by-faemiyah

APP_FULLNAME="piNp"
APP_COPYRIGHT="Faemiyah"
APP_DESC="4k intro by Faemiyah released in 2004"

APP_EXE="pinp-by-faemiyah"

function run()
{
	backuppwd=$(pwd)
	cd /usr/bin/
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
