#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nitte-by-passion

APP_FULLNAME="Nitte"
APP_COPYRIGHT="Passion"
APP_DESC="intro ranked 3rd at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
