#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=a500homage-by-complex

APP_FULLNAME="A500 Homage"
APP_COPYRIGHT="Complex"
APP_DESC="Intro ranked 11th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
