#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=s-by-skarla

APP_FULLNAME="S"
APP_COPYRIGHT="skarla"
APP_DESC="intro ranked 17th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
