#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=pixeledpleasure-by-them-disk

APP_FULLNAME="Pixeled Pleasure"
APP_COPYRIGHT="Them"
APP_DESC="Demo Released in 1991"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
