#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=pixeledpleasure-by-them-disk

APP_FULLNAME="Pixeled Pleasure"
APP_COPYRIGHT="Them"
APP_DESC="Demo Released in 1991"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
