#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=robotnik-by-rage

APP_FULLNAME="Robotnik"
APP_COPYRIGHT="Rage"
APP_DESC="demo ranked 2nd at The Gathering 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
