#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fortnight-by-mfx

APP_FULLNAME="Fortnight"
APP_COPYRIGHT="mfx"
APP_DESC="Demo by Desire, released in 2001"

APP_EXE="fortnight-by-mfx"

function run()
{
	backuppwd=$(pwd)
	cd /usr/bin/
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
