#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=flowerpower-by-anarchy-amiga-whd

APP_FULLNAME="Flower Power"
APP_COPYRIGHT="Anarchy"
APP_DESC="Demo by Anarchy,released in 1992"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
