#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=bugelplasma-by-xq

APP_FULLNAME="Bugelplasma"
APP_COPYRIGHT="xq"
APP_DESC="Demo by xq, released in 2018"

APP_EXE="buegelperle"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
