#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=crazysexycool-by-essence

APP_FULLNAME="Crazy Sexy Cool"
APP_COPYRIGHT="essence"
APP_DESC="demo ranked 5 at the Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
