#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=ishotkurtcobain-by-razor1911

APP_FULLNAME="I Shot Kurt Cobain"
APP_COPYRIGHT="Razor 1911"
APP_DESC="intro released at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
