#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=enigma-by-phenomena

APP_FULLNAME="Enigma"
APP_COPYRIGHT="Phenomena"
APP_DESC="Demo ranked 1s at Anarchy Easter Party 1991"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
