#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=ringingadoorbell-by-movement

APP_FULLNAME="Ringing a Doorbell"
APP_COPYRIGHT="Movement"
APP_DESC="demo released in october 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
