#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=anthemforanewrobotdawn-by-gasman

APP_FULLNAME="Anthem for a New Robot Dawn"
APP_COPYRIGHT="Gasman"
APP_DESC="demo by Gasman released in 2012"

APP_EXE="robot.py"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
