#!/bin/bash -e

source common-install-function

domain=bashoholics-by-boozoholics

APP_FULLNAME="Bashoholics"
APP_COPYRIGHT="boozoholics"
APP_DESC="demo by boozoholics released in 2006"

APP_EXE="bashoholics.sh"

function run()
{
	backuppwd=$(pwd)
	cd ../..
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
