#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=saturneparty2invitation-by-saturne

APP_FULLNAME="Saturne Party 2 Invitation"
APP_COPYRIGHT="Saturne"
APP_DESC="Intro invit by Saturne released in 1994-02-03"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
