#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=saturneparty2invitation-by-saturne

APP_FULLNAME="Saturne Party 2 Invitation"
APP_COPYRIGHT="Saturne"
APP_DESC="Intro invit by Saturne released in 1994-02-03"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
