#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=alien-by-scoopex

APP_FULLNAME="Alien"
APP_COPYRIGHT="Scoopex"
APP_DESC="demo ranked 2nd at Abduction 1995"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
