#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=vip-by-popsyteam

APP_FULLNAME="VIP 1"
APP_COPYRIGHT="Popsy Team"
APP_DESC="invit demo ranked 2nd at the Arf!Party 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "VIP.EXE" "VIP.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
