#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=vip-by-popsyteam

APP_FULLNAME="VIP 1"
APP_COPYRIGHT="Popsy Team"
APP_DESC="invit demo ranked 2nd at the Arf!Party 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "VIP.EXE" "VIP.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
