#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=iz-us-by-replay

APP_FULLNAME="IZ-US"
APP_COPYRIGHT="replay"
APP_DESC="demo ranked 5th at Hype 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "IZ-US.EXE" "IZ-US.EXE"
	NSH_InstallRWFileInTmp "DOS4GW.EXE" "DOS4GW.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
