#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=iz-us-by-replay

APP_FULLNAME="IZ-US"
APP_COPYRIGHT="replay"
APP_DESC="demo ranked 5th at Hype 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "IZ-US.EXE" "IZ-US.EXE"
	NSH_InstallRWFileInTmp "DOS4GW.EXE" "DOS4GW.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
