#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=vision-by-oxygene

APP_FULLNAME="vision"
APP_COPYRIGHT="Oxygene"
APP_DESC="demo ranked 2nd at The Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
