#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=secretultradry-by-broncs

APP_FULLNAME="Secret Ultra Dry"
APP_COPYRIGHT="Broncs"
APP_DESC="demo ranked 3rd at Demobit 2000"
APP_EXE="SUD.EXE"
APP_SETSOUND="SUD.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
