#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fridayateight-by-polkabrothers

APP_FULLNAME="Friday at Eight"
APP_COPYRIGHT="Polka Brothers"
APP_DESC="Demo ranked 3rd at The Gathering 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
