#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=thetetrisintro-by-melondezignandcrystal

APP_FULLNAME="The tetris intro (legalize it 3)"
APP_COPYRIGHT="Melon Dezign and Crystal"
APP_DESC="Intro ranked 1st at The PArty 1992"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
