#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=tint-by-theblacklotus

APP_FULLNAME="Tint"
APP_COPYRIGHT="The Black Lotus"
APP_DESC="Demo ranked 1st at The Gathering 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
