#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=40partyintro-by-facetspussyanddesire

APP_FULLNAME="40k Party Intro"
APP_COPYRIGHT="Facet's Pussy and Desire"
APP_DESC="intro ranked 19th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
