#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=manualoverride-by-subacid

APP_FULLNAME="Manual Override"
APP_COPYRIGHT="Subacid"
APP_DESC="demo ranked 6th at The Gathering 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
