#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=outlineinvitation-by-desiretheundeadsceners

APP_FULLNAME="Outline Invitation"
APP_COPYRIGHT="Desire & The Undead Sceners"
APP_DESC="Demo by Desire & The Undead Sceners, released in 2017"

APP_EXE="tus_dsr-outline_invite"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
