#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=savior-by-laserboyhotmultimedia

APP_FULLNAME="Savior"
APP_COPYRIGHT="Laserboy + Hot Multimedia"
APP_DESC="demo by Laserboy + Hot Multimedia released in 2014"

APP_EXE="run.sh"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
