#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=daclone-by-halcyon

if [ $(which gettext) ]; then
	gettext="gettext --domain=$domain -s --"
else
	gettext=echo
fi

function usage()
{
	$gettext "Usage: daclone-by-halcyon [OPTION]"
	$gettext "Start Da Clone - demo released in june 1995"
	echo
	$gettext "    --help       display this help and exit"
	$gettext "    --fullscreen start game in fullscreen (Ctrl-F9 to quit)"
	$gettext "    --debug      start the dosbox environnement without running the demo"
	$gettext "    --version    display version information and exit"
}

function version()
{
	$gettext "daclone-by-halcyon"
	$gettext "Copyright (C) Halcyon "
	$gettext "Dosbox Copyright (C) Dosbox Team"
}

function run()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp KUVA.DAT KUVA.DAT
	/usr/bin/dosbox-x -conf /usr/share/${domain}/${domain}.conf $2
	NSH_RemoveTmpDomainDir
}

function run_debug()
{
	NSH_CreateTmpDomainDir
	NSH_SetDebugDOSBOX
	NSH_InstallRWFileInTmp KUVA.DAT KUVA.DAT
	/usr/bin/dosbox-x -conf  /tmp/${domain}_debug.conf
	NSH_RemoveDebugDOSBOX
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run $domain 
else
	case "$1" in
	--help)
		usage
		;;
	--fullscreen)
		run $domain -fullscreen
		;;
	--debug)
		run_debug 
		;;
	--version)
		version
		;;
	*)
		usage
		exit 1
		;;
	esac
fi

exit 0
