#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=daclone-by-halcyon

APP_FULLNAME="Da Clone"
APP_COPYRIGHT="Halcyon"
APP_DESC="demo released in june 1995"
APP_EXE="DA_CLONE.EXE"
APP_SETSOUND="DA_CLONE.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "KUVA.DAT" "KUVA.DAT"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
