#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=realsurreal-by-impactdk

APP_FULLNAME="real surreal"
APP_COPYRIGHT="Impact DK"
APP_DESC="demo ranked 16th at The Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
