#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=secretrooms-by-mikaelfyrekandphiliplafleur

APP_FULLNAME="Secret Rooms"
APP_COPYRIGHT="Mikael Fyrek and Philip Lafleur"
APP_DESC="demo by Mikael Fyrek and Philip Lafleur released in 2014"

APP_EXE="secret-rooms-linux64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE} -w 1280x720
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
