#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=hypnotic-by-exobit

APP_FULLNAME="Hypnotic"
APP_COPYRIGHT="Exobit"
APP_DESC="demo ranked 2nd at Euskal 1996"
APP_EXE="HYPNOTIC.EXE"
APP_SETSOUND="HYPNOTIC.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "HYPNOTIC.DAT" "HYPNOTIC.DAT"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
