#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=phenotype-by-purge

APP_FULLNAME="Phenotype"
APP_COPYRIGHT="purge"
APP_DESC="demo ranked 3rd at Wired 1995"
APP_EXE="PHENOTYP.EXE"
APP_SETSOUND="PHENOTYP.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "HER.DMF" "HER.DMF"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
