#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=mindflow-by-stellar

APP_FULLNAME="Mindflow"
APP_COPYRIGHT="Stellar"
APP_DESC="Demo ranked 1st at Assembly 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
