#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=dxproject-by-realtech

APP_FULLNAME="DX Project"
APP_COPYRIGHT="realtech"
APP_DESC="demo ranked 3rd at Assembly 1995"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
