#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=laufertro-by-apex

APP_FULLNAME="Laufer Tro"
APP_COPYRIGHT="Apex"
APP_DESC="Intro ranked 22th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
