#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=astral-blur-by-tbl

APP_FULLNAME="Astral Blur"
APP_COPYRIGHT="The Black Lotus"
APP_DESC="demo ranked 3rd at The Gathering 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
