#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=smokebomb-by-ozone

APP_FULLNAME="Smoke Bomb"
APP_COPYRIGHT="Ozone"
APP_DESC="Demo ranked 3rd at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
