#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=smokebomb-by-ozone

APP_FULLNAME="Smoke Bomb"
APP_COPYRIGHT="Ozone"
APP_DESC="Demo ranked 3rd at Mekka and Symposium 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
