#! /bin/sh
set -e

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

# Chatty requires at least Java8 to run
find_java_runtime java8

cd /usr/share/kryoflux/
run_java -jar kryoflux-ui.jar "$@"
