#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=babylon-by-psychicmonks

APP_FULLNAME="Babylon"
APP_COPYRIGHT="Psychics Monks"
APP_DESC="demo by psychis monks released at Assembly 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
