#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=closer-by-cncd

APP_FULLNAME="closer"
APP_COPYRIGHT="Carillon and Cyberiad"
APP_DESC="demo ranked 1st at The Party 1995"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
