#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=firstanniversary-by-melondezign

APP_FULLNAME="First Anniversary"
APP_COPYRIGHT="Melon Dezign"
APP_DESC="intro released in october 1992"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
