#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=firstanniversary-by-melondezign

APP_FULLNAME="First Anniversary"
APP_COPYRIGHT="Melon Dezign"
APP_DESC="intro released in october 1992"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
