#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=gospelkaraoke-by-complex

APP_FULLNAME="Gospel Karaoke"
APP_COPYRIGHT="Complex"
APP_DESC="Demo released in june 1992"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
