#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nedexamples-by-bartoshe/dragonhell

APP_FULLNAME="Ned Dragon Hell"
APP_COPYRIGHT="bartoshe"
APP_DESC="Demo by bartoshe, released in 2016"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain}
	nedplayer
	cd $backuppwd
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
