#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=harmagedon-by-infect-amiga-whd

APP_FULLNAME="Harmagedon"
APP_COPYRIGHT="Infect"
APP_DESC="Demo by Infect, released in 1993"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
