#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=doodledoo-by-virtualdreamsandfairlight

APP_FULLNAME="Doodle-Doo"
APP_COPYRIGHT="Virtual Dreams and Fairlight"
APP_DESC="intro ranked 4th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
