#!/bin/sh
# autopkgtest check: Builds a small application against libpng, checking
# if it compiles, links and runs successfully.
# Author: Rafaè©» Cieè´‹lak <rafalcieslak256@ubuntu.com> 

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > build_test.c
#include <png.h>
int main(int argc, char** argv) {
    png_structp png_ptr = NULL;
    //Just creating a simple write struct.
    png_ptr = png_create_write_struct (PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
    if(!png_ptr) return 1;
    return 0;
}
EOF
gcc -o build_test build_test.c -lpng
echo "build: OK"
[ -x build_test ]
./build_test
echo "run: OK"
