#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=strata-by-luminaire

APP_FULLNAME="Strata"
APP_COPYRIGHT="Luminaire"
APP_DESC="4k intro by tkln, released in 2018"

APP_EXE="strata-by-luminaire"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain} || exit
	LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}|aplay -f cd
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
