#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=booo-by-melondezign

APP_FULLNAME="Booo"
APP_COPYRIGHT="Melon Dezign"
APP_DESC="Demo released in frebruary 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
