#!/bin/bash -e

domain=vertex-by-tatanka-win32

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_wine2
