#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=nexus7-by-andromeda

APP_FULLNAME="Nexus-7"
APP_COPYRIGHT="Andromeda"
APP_DESC="Demo ranked 1st at The Party 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
