#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=darkside-by-theblacklotus-amiga-whd

APP_FULLNAME="Dark Side"
APP_COPYRIGHT="The Black Lotus"
APP_DESC="Demo by The Black Lotus,released in 1996"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
