#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=kannykkamafia-by-revengetheperse

APP_FULLNAME="kännykkä mafia"
APP_COPYRIGHT="Revenge the Perse"
APP_DESC="demo ranked 10th at Elevator 2000"

function prerun()
{
	NSH_CreateTmpDomainDir
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
