#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=kannykkamafia-by-revengetheperse

APP_FULLNAME="kännykkä mafia"
APP_COPYRIGHT="Revenge the Perse"
APP_DESC="demo ranked 10th at Elevator 2000"
APP_EXE="MAFIA.EXE"
APP_SETSOUND="MAFIA.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
