#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=amirun-by-thesolarisagency

APP_FULLNAME="AmiRun"
APP_COPYRIGHT="The Solaris Agency"
APP_DESC="Demo by The Solaris Agency, released in 2020"

APP_EXE="AmiRun_v1.1.5_Linux.x86_64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
