#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=okiedokie-by-soopadoopa

APP_FULLNAME="okiedokie"
APP_COPYRIGHT="soopadoopa"
APP_DESC="demo ranked 4th at the Gathering 1999"
APP_EXE="DEMO.EXE"
APP_SETSOUND="DEMO.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
