#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=sevenance-by-joga

APP_FULLNAME="Sevenance"
APP_COPYRIGHT="joga"
APP_DESC="4k intro by joga, released in 2016"

APP_EXE="sevenance-1920x1080"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
