#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=jade-by-eclipse

APP_FULLNAME="Jade"
APP_COPYRIGHT="Eclipse"
APP_DESC="ranked 1st at the Volcanic party 1995"
APP_EXE="JADE.EXE"
APP_SETSOUND="JADE.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
