#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=outofspice-by-kinkyproductions

APP_FULLNAME="out of spice"
APP_COPYRIGHT="Kinky Porductions"
APP_DESC="demo ranked 2nd at Abduction 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
