#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=presidenttipelia-by-humppamachines-revengeoftheperse

APP_FULLNAME="presidenttipeliä"
APP_COPYRIGHT="Humppamachines & Revenge the Perse"
APP_DESC="demo ranked 9th at Elevator 2000"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
