#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=summertime-by-resistance

APP_FULLNAME="Summertime"
APP_COPYRIGHT="Resistance"
APP_DESC="demo by Resistance released in 2010"

APP_EXE="summertime_lin64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE} window
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
