#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=blur-by-focusdesign

APP_FULLNAME="blur"
APP_COPYRIGHT="Focus Design"
APP_DESC="intro ranked 13th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
