#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=40kintro-by-craptors

APP_FULLNAME="40k intro"
APP_COPYRIGHT="Craptors"
APP_DESC="intro ranked 14th at The Party 1994"

function run()
{
	NSH_CreateWHDSaves
	/usr/bin/fs-uae /usr/share/$domain/$domain.fs-uae $1
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		run --fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
