#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=40kintro-by-craptors

APP_FULLNAME="40k intro"
APP_COPYRIGHT="Craptors"
APP_DESC="intro ranked 14th at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
