#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lightningroadtoliquidradiator-by-theundeadsceners

APP_FULLNAME="Lightning Road To Liquid Radiator"
APP_COPYRIGHT="The Undead Sceners"
APP_DESC="demo by The Undead Sceners released in 2013"

APP_EXE="lr2lr"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	tail -n+3 ${APP_EXE} | xzcat > /tmp/d01;chmod +x /tmp/d01
	/tmp/d01 1280 720
	rm /tmp/d01
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
