#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=flashback-by-thecarebears-atari

APP_FULLNAME="Flashback"
APP_COPYRIGHT="The Carebears"
APP_DESC="demo by The Carebears released in 1993"

function run()
{
	/usr/bin/hatari --memsize 2 /usr/share/${domain}/FLASH.MSA
}

source /usr/share/common-install-function-ddebs/endscript_atarist
