#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=ephemera-by-approximate

APP_FULLNAME="ephemera"
APP_COPYRIGHT="Approximate"
APP_DESC="demo by Approximate released in 2009"

APP_EXE="ephemerafinal32bit"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	SDL_VIDEODRIVER=x11 LD_LIBRARY_PATH=./:/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
