#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=professionalmagickwrestler-by-gzrrplox

APP_FULLNAME="Professional Magick Wrestler"
APP_COPYRIGHT="Gzrrplox"
APP_DESC="demo by Gzrrplox released in 2011"

APP_EXE="pmw-960x600-windowed"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
