#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=stars-wondersoftheworld-by-noon

APP_FULLNAME="Stars: Wonders of the World"
APP_COPYRIGHT="noon"
APP_DESC="demo ranked 1st at Assembly 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "STARS.EXE" "STARS.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
