#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=4kker-by-checkpoint-atari

APP_FULLNAME="4KKER"
APP_COPYRIGHT="Checkpoint"
APP_DESC="demo by Checkpoint released in 2006"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/$domain/harddrive
}

source /usr/share/common-install-function-ddebs/endscript_atarist
