#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=attheparty-by-clous

APP_FULLNAME="At the party"
APP_COPYRIGHT="c-lous"
APP_DESC="intro ranked 10th at The PArty 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
