#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=totem-issue1-by-jff

APP_FULLNAME="TOTEM issue #1"
APP_COPYRIGHT="Just For Fun"
APP_DESC="this is the first and last issue of Totem"
APP_EXE="TOTEM.EXE"
APP_SETSOUND="TOTEM.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "TOTEM.EXE" "TOTEM.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
