#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=4getful-by-gwem-atari

APP_FULLNAME="4getful"
APP_COPYRIGHT="gwEm"
APP_DESC="demo by gwEm released in 2006"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/$domain/harddrive
}

source /usr/share/common-install-function-ddebs/endscript_atarist
