#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=chaosland-by-virtualdreamsandfairlight

APP_FULLNAME="Chaosland"
APP_COPYRIGHT="Virtual Dreams and Fairlight"
APP_DESC="intro ranked 1st at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
