#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=9fingers-by-spaceballs-whdload

APP_FULLNAME="9 Fingers"
APP_COPYRIGHT="Spaceballs"
APP_DESC="Amiga trackmo ranked #4 at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
