#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=hugeupsidedownsquirrel-by-candela

APP_FULLNAME="Huge Upside Down Squirrel"
APP_COPYRIGHT="Candela"
APP_DESC="demo by Candela released in 2011"

APP_EXE="demo_64"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE} -w 1280 -h 720 -win
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
