#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=adn-by-oxygene

APP_FULLNAME="ADN"
APP_COPYRIGHT="Oxygene"
APP_DESC="Demo ranked 1st at 3S Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
