#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=solex-by-oxygene

APP_FULLNAME="solex"
APP_COPYRIGHT="Oxygene"
APP_DESC="demo released in may 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
