#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=just-by-legenddesign

APP_FULLNAME="Just"
APP_COPYRIGHT="legend design"
APP_DESC="demo ranked 2nd at Wired 1995"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
