#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=dawn-by-jamm

APP_FULLNAME="Dawn"
APP_COPYRIGHT="jamm"
APP_DESC="intro 64k ranked 1st at Juhla 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
