#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=censurationii-by-therapy

APP_FULLNAME="Censuration II"
APP_COPYRIGHT="Therapy"
APP_DESC="Intro ranked 23rd at The Party 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
