#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=air-by-xes

APP_FULLNAME="Air"
APP_COPYRIGHT="Xes"
APP_DESC="intro 64k ranked 3rd at Abduction 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
