#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=air-by-xes

APP_FULLNAME="Air"
APP_COPYRIGHT="Xes"
APP_DESC="intro 64k ranked 3rd at Abduction 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
