#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=muhammad-by-bbagf

APP_FULLNAME="Muhammad"
APP_COPYRIGHT="Breakin, Bliss, Abullalah, Grip, Fugue"
APP_DESC="demo ranked 2nd at Hype 1999"
APP_EXE="MUHAMMAD.EXE"
APP_SETSOUND="MUHAMMAD.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
