#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=globaltrash-by-silents-disk

APP_FULLNAME="Global Trash"
APP_COPYRIGHT="Silents"
APP_DESC="demo released 1991-04-26 on Amiga Summit Convention"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
