#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=globaltrash-by-silents-disk

APP_FULLNAME="Global Trash"
APP_COPYRIGHT="Silents"
APP_DESC="demo released 1991-04-26 on Amiga Summit Convention"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
