#!/bin/bash -e

domain=imagine-by-dizzlogic

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

APP_FULLNAME="imagine"
APP_COPYRIGHT="Dizzlogic"
APP_DESC="demo ranked 11 at Dreamhack 2000"

if [ $(which gettext) ]; then
	gettext="gettext --domain=$domain -s --"
else
	gettext=echo
fi

function usage()
{
	$gettext "Start $APP_FULLNAME - $APP_DESC"
	echo
	$gettext "Usage: $0 [option]"
	$gettext "Options :"
	$gettext "    --help                            display this help and exit"
	$gettext "    --setdesktop                      set to desktop and run"
	$gettext "    --setwindow                       set to window mode and run"
	$gettext "    --setwine [wine version]          set to another wine"
	$gettext "    --reset                           reset to the default wine"
	$gettext "    --version                         display version information and exit"
}

function version()
{
	$gettext $0
	$gettext "Copyright (C) $APP_COPYRIGHT"
	$gettext "PlayOnLinux Copyright (C) PlayOnLinux Team"
}

function prepare_first_run() 
{
	NSH_RemoveShortcutWINE "$APP_FULLNAME"
	/usr/share/playonlinux/playonlinux-bash /usr/share/${domain}/${domain}_userinstall.pol
	echo ${domain} set to wine $polarch $polwine in $polscreenmode mode
}

function run()
{
	/usr/share/playonlinux/playonlinux --run "$APP_FULLNAME" %F
}

if [ "$#" -gt "3" ]; then
	usage
	exit 1
elif [ "$#" -lt "1" ]; then
	if [ ! -e "$HOME/.PlayOnLinux/shortcuts/$APP_FULLNAME" ]
	then
		export polscreenmode
		export polwine
		prepare_first_run
		run
	else 
		run
	fi
else
	case "$1" in
	--help)
		usage
		;;
	--version)
		version
		;;
	--setdesktop)
		export polscreenmode="desktop"
		export polwine
		prepare_first_run
		;;
	--setwindow)
		export polscreenmode="window"
		export polwine
		prepare_first_run
		;;
	--setwine)
		if [ -z "$2" ]
		then
			usage
			exit 1
		fi
		export polscreenmode
		export polwine="$2"
		prepare_first_run
		;;
	--reset)
		export polscreenmode
		export polwine
		prepare_first_run
		;;
	*)
		usage
		exit 1
		;;
	esac
fi

exit 0
