#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=32kilobytesofforkle-by-romanshuvalov

APP_FULLNAME="32 kilobytes of Forkle"
APP_COPYRIGHT="Roman Shuvalov"
APP_DESC="game by Roman Shuvalov released in 2016"

APP_EXE="f32k_linux"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
