#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=goldorak-by-realtime

APP_FULLNAME="Goldorak"
APP_COPYRIGHT="Realtime"
APP_DESC="demo ranked 1st at somewhere in holland 1995"
APP_EXE="GOLDORAK.EXE"
APP_SETSOUND="GOLDORAK.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "GOLDORAK.EXE" "GOLDORAK.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
