#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=paper-by-psychiclink-acme

APP_FULLNAME="Paper"
APP_COPYRIGHT="Psychic Link & Acme"
APP_DESC="intro ranked 1st at wired 1996"
APP_EXE="PAPER.EXE"
APP_SETSOUND="PAPER.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
