#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=ting-by-movement

APP_FULLNAME="Ting"
APP_COPYRIGHT="Movement"
APP_DESC="intro ranked 4th at Assembly 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
