#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=progress3-by-kstorm

APP_FULLNAME="progress 3"
APP_COPYRIGHT="K-Storm"
APP_DESC="Demo by K-Storm, released in 2018"

APP_EXE="progress_3"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain} || exit
	SDL12COMPAT_OPENGL_SCALING=1 LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd || exit
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
