#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=helloworld-by-krekola

APP_FULLNAME="Hello World"
APP_COPYRIGHT="krekola"
APP_DESC="demo by krekola released in 2006"
APP_EXE="fs_k-hello_world"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
