#!/bin/bash -e

domain=win32-squish-by-and

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_wine2
