#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=chapichapo-by-aegiscorp

APP_FULLNAME="Chapi Chapo"
APP_COPYRIGHT="Aegis Corp."
APP_DESC="demo ranked 3rd at the Saturn Party 1996"
APP_EXE="CHAPI.EXE"
APP_SETSOUND="CHAPI.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
