#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=interference-by-sanity

APP_FULLNAME="Interference"
APP_COPYRIGHT="Sanity"
APP_DESC="Demo released in april 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
