#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=interference-by-sanity

APP_FULLNAME="Interference"
APP_COPYRIGHT="Sanity"
APP_DESC="Demo released in april 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
