#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=shianlee-by-bomb

APP_FULLNAME="Shian Lee"
APP_COPYRIGHT="Bomb!"
APP_DESC="demo ranked 1st at Volcanic 1997"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
