#!/bin/bash -e

source common-install-function

domain=real-by-complex

APP_FULLNAME="Real"
APP_COPYRIGHT="Complex"
APP_DESC="Demo ranked 1st at Saturne 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
