#!/bin/bash -e

source common-install-function

domain=real-by-complex

APP_FULLNAME="Real"
APP_COPYRIGHT="Complex"
APP_DESC="Demo ranked 1st at Saturne 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunAMIGA
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		NSH_RunAMIGA -fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
