#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=technotracks2-by-trojan-disk

APP_FULLNAME="Techno Tracks 2"
APP_COPYRIGHT="Trojans"
APP_DESC="Released at The Gathering 1993"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
