#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=technotracks2-by-trojan-disk

APP_FULLNAME="Techno Tracks 2"
APP_COPYRIGHT="Trojans"
APP_DESC="Released at The Gathering 1993"

function run()
{
	/usr/bin/fs-uae /usr/share/$domain/$domain.fs-uae $1
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		run --fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
