#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=8bitwonderland-by-kakiarts

APP_FULLNAME="8-Bit Wonderland"
APP_COPYRIGHT="Kakiarts"
APP_DESC="demo by Kakiarts released in 2007"
APP_EXE="8bit-linux-x86"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
