#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=iwgiwrm-by-dentifrice

APP_FULLNAME="If I was a Girl, I would rape myself"
APP_COPYRIGHT="dentifrice"
APP_DESC="intro released at Saturne Party 1996"
APP_EXE="DEN-GIRL.EXE"
APP_SETSOUND="DEN-GIRL.EXE"

function prerun()
{
	NSH_CreateTmpDomainDir
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
