#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=insectjazz-by-damage

APP_FULLNAME="Insect Jazz"
APP_COPYRIGHT="damage"
APP_DESC="demo ranked 3rd at the Elevator 2000"
APP_EXE="INSECT.EXE"
APP_SETSOUND="INSECT.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
