#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=mleinandsharkywedtro-by-limpninja

APP_FULLNAME="mlein and sharky- wedtro"
APP_COPYRIGHT="Limp Ninja"
APP_DESC="demo by Limp Ninja released in 2007"
APP_EXE="exe"

function run()
{
	backuppwd=$(pwd)
	cd /usr/share/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
