#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=mindexpanding-by-melondezign

APP_FULLNAME="Mind Expanding"
APP_COPYRIGHT="Melon Dezign"
APP_DESC="demo released 22 at The Party 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
