#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=gasoline-by-recreation

APP_FULLNAME="gasoline"
APP_COPYRIGHT="Recreation"
APP_DESC="demo ranked 1st at Assembly 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "GASOLINE.EXE" "GASOLINE.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
