#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=starcondom-by-hexodnova

APP_FULLNAME="Star Condom"
APP_COPYRIGHT="Hexod & Nova"
APP_DESC="Released: 1994-04-23 on Saturne Party 2 1994, ranked 9 in the Demo competition"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
