#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=3secondsofdelight-by-movement

APP_FULLNAME="3 Seconds of Delight"
APP_COPYRIGHT="Movement"
APP_DESC="Intro released in 1994"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
