#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=perkele-by-movement

APP_FULLNAME="Perkele"
APP_COPYRIGHT="Movement"
APP_DESC="intro released in ????"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
