#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=harpers-friend-by-proxima

APP_FULLNAME="Harper's Friend"
APP_COPYRIGHT="Proxima"
APP_DESC="demo ranked 10th at the Gathering 1999"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "DEMO.EXE" "DEMO.EXE"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
