#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=alieninvasion-by-nectarine

APP_FULLNAME="Alien Invasion"
APP_COPYRIGHT="Nectarine"
APP_DESC="demo by Nectarine released in 2010"

APP_EXE="alien_invasion-frame.sh"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/x86_64-linux-gnu/${domain}
	LD_LIBRARY_PATH=./:/usr/lib/x86_64-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
