#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=kayttokuksa-by-taat

APP_FULLNAME="Käyttökuksa"
APP_COPYRIGHT="tAAt"
APP_DESC="demo ranked 4th at Assembly 1999"
APP_EXE="KUKSA.EXE"
APP_SETSOUND="KUKSA.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
