#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=machineofmadness-by-dublus

APP_FULLNAME="Machine of Madness"
APP_COPYRIGHT="dublus"
APP_DESC="demo ranked 1st at Assembly 1996"
APP_EXE="MACHINES.EXE"
APP_SETSOUND="MACHINES.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
