#!/bin/bash -e

domain=further-by-moppiproductions-win32

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

function prerun()
{
	winetricks vcrun6
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_wine2
