#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=switchback-by-rebels

APP_FULLNAME="Switchback"
APP_COPYRIGHT="Rebels"
APP_DESC="demo ranked 1st at Doom's Day Party 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
