#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=newyear2-by-outbreak

APP_FULLNAME="Newyear2"
APP_COPYRIGHT="Outbreak"
APP_DESC="demo by Outbreak- released in 2004"

APP_EXE="newyear2-elf"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	LD_LIBRARY_PATH=. ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
