#!/bin/bash -e

domain=win32-fr03monochromieistnichts-by-farbrausch

source /usr/share/common-install-function-ddebs/common-install-function
source /etc/$domain.conf

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp fvs32dbg.txt fvs32dbg.txt
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_wine
