#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=surfingonthejazzwave-by-thegroovingbrothers-amiga-disk

APP_FULLNAME="surfing on the jazz wave"
APP_COPYRIGHT="the grooving brothers"
APP_DESC="Demo by the grooving brothers,released in 1994"

function run()
{
	/usr/bin/fs-uae /usr/share/$domain/$domain.fs-uae $1
}

if [ "$#" -gt "1" ]; then
	 NSH_std_usage_AMIGA
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage_AMIGA
		;;
	--fullscreen)
		run --fullscreen
		;;
	--version)
		NSH_version_AMIGA
		;;
	*)
		NSH_std_usage_AMIGA
		exit 1
		;;
	esac
fi

exit 0
