#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=surfingonthejazzwave-by-thegroovingbrothers-amiga-disk

APP_FULLNAME="surfing on the jazz wave"
APP_COPYRIGHT="the grooving brothers"
APP_DESC="Demo by the grooving brothers,released in 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
