#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=hollow-by-dsk

APP_FULLNAME="Hollow"
APP_COPYRIGHT="dSK"
APP_DESC="intro ranked 3rd at Fallas Party 2000"
APP_EXE="HOLLOW.EXE"
APP_SETSOUND="HOLLOW.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
