#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=brama-by-norferin

APP_FULLNAME="Brama"
APP_COPYRIGHT="Norferin"
APP_DESC="demo ranked 3rd at Analogue 1999"
APP_EXE="NFNBRAMA.EXE"
APP_SETSOUND="NFNBRAMA.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
