#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fashion-by-logicdesign

APP_FULLNAME="Fashion"
APP_COPYRIGHT="Logic Design"
APP_DESC="demo ranked 1st at X 1996"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
