#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=codliveroild-by-damones

APP_FULLNAME="Cod Liver Oil"
APP_COPYRIGHT="Damones"
APP_DESC="demo ranked 2nd at Assembly 1999"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
