#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=theufoproject-by-orangenoon

APP_FULLNAME="The UFO Project"
APP_COPYRIGHT="orange and noon"
APP_DESC="intro 64k released in december 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "UFO.UFO" "UFO.UFO"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

source /usr/share/common-install-function-ddebs/endscript_dos
