#!/bin/bash -e

source  /usr/share/common-install-function-ddebs/common-install-function

domain=theufoproject-by-orangenoon

APP_FULLNAME="The UFO Project"
APP_COPYRIGHT="orange and noon"
APP_DESC="intro 64k released in december 1995"

function prerun()
{
	NSH_CreateTmpDomainDir
	NSH_InstallRWFileInTmp "UFO.UFO" "UFO.UFO"
}

function postrun()
{
	NSH_RemoveTmpDomainDir
}

if [ "$#" -gt "1" ]; then
	NSH_std_usage_DOSBOX
	exit 1
elif [ "$#" -lt "1" ]; then
	NSH_RunDOSBOX
else
	case "$1" in
	--help)
		NSH_std_usage_DOSBOX
		;;
	--fullscreen)
		NSH_RunDOSBOXX -fullscreen
		;;
	--debug)
		NSH_RunDebugDOSBOX
		;;
	--version)
		NSH_version_DOSBOX
		;;
	*)
		NSH_std_usage_DOSBOX
		exit 1
		;;
	esac
fi

exit 0
