#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=fastlove-by-wamma

APP_FULLNAME="Fastlove"
APP_COPYRIGHT="wAMMA"
APP_DESC="demo by wAMMA released in 2008"

APP_EXE="wamma-fastlove -w"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
