#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=realityhasnomeaning-by-balance

APP_FULLNAME="Reality Has No Meaning"
APP_COPYRIGHT="balance"
APP_DESC="intro ranked 4th at The Gathering 1993"

function prerun()
{
	NSH_CreateWHDSaves
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
