#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=atlantis-by-mooze

APP_FULLNAME="Atlantis"
APP_COPYRIGHT="Mooze"
APP_DESC="a mooze contribution to assembly 1996 democompo"
APP_EXE="ATLANTIS.EXE"
APP_SETSOUND="ATLANTIS.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
