#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=final-by-unknown-atari

APP_FULLNAME="final"
APP_COPYRIGHT="unknown"
APP_DESC="demo by unknown released in 1997"

function run()
{
	/usr/bin/hatari --machine ste -s 2 -d /usr/share/$domain/harddrive
}

source /usr/share/common-install-function-ddebs/endscript_atarist
