#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=purple-by-youthuprising

APP_FULLNAME="Purple"
APP_COPYRIGHT="Youth Uprising"
APP_DESC="demo by Youth Uprising released in 2007"
APP_EXE="purple.linux"

function run()
{
	backuppwd=$(pwd)
	cd /usr/lib/i386-linux-gnu/${domain}
	./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
