#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=juice-by-psychiclink

APP_FULLNAME="Juice"
APP_COPYRIGHT="Psychic Link"
APP_DESC="demo ranked 2nd at Assembly 1995"
APP_EXE="JUICE.EXE"
APP_SETSOUND="JUICE.EXE"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_dos
