#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=lethaldose2-by-faculty-disk

APP_FULLNAME="Lethal Dose 2"
APP_COPYRIGHT="Faculty"
APP_DESC="demo ranked 1st at The Hammering 1994"

function prerun()
{
	sleep 1
}

function postrun()
{
	sleep 1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
