#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=plays2unlimited-by-scoopex

APP_FULLNAME="Plays 2 unlimited"
APP_COPYRIGHT="Scoopex"
APP_DESC="released at The Gathering 1993"

function prerun()
{
	NSH_CreateWHDSaves
	NSH_ExtractDH1
}

function postrun()
{
	NSH_RemoveDH1
}

source /usr/share/common-install-function-ddebs/endscript_amiga
