#!/bin/bash -e

source /usr/share/common-install-function-ddebs/common-install-function

domain=bioterrorism-by-belowabsolutezero

APP_FULLNAME="Bioterrorism"
APP_COPYRIGHT="Below Absolute Zero"
APP_DESC="demo by Below Absolute Zero released in 2013"
APP_EXE="bioterrorism-by-belowabsolutezero"

function run()
{
	backuppwd=$(pwd)
	cd /usr/bin/
	LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/sdl12-compat/ ./${APP_EXE}
	cd $backuppwd
}


if [ "$#" -gt "1" ]; then
	 NSH_std_usage
	exit 1
elif [ "$#" -lt "1" ]; then
	run
else
	case "$1" in
	--help)
		NSH_std_usage
		;;
	*)
		NSH_std_usage
		exit 1
		;;
	esac
fi

exit 0
